#! /bin/sh

msg="
Hello! If you are seeing this message, you probably need to configure some stuff around.

Check out the ${HOME}/.config/bspwm/bspwmrc and ${HOME}/.config/bspwm/sxhkdrc files to
change the configurations and keybindings. Feel free to install a window manager/desktop
environment of your preference.

Press Win+Enter to open a terminal emulator or Win+d to open the application launcher,
use Win+[1-9] to move around workspaces. Btw Win+w closes windows :).
"

kitty --hold echo $msg 
